// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Granit contributors

// 由 Granit 测试夹具工具生成。

constexpr std::array<std::byte, 32> minimal_vertex_id{
  std::byte{0xfa},
  std::byte{0xdc},
  std::byte{0xe2},
  std::byte{0xea},
  std::byte{0x31},
  std::byte{0x7a},
  std::byte{0xe6},
  std::byte{0x70},
  std::byte{0xad},
  std::byte{0xa7},
  std::byte{0x5c},
  std::byte{0xee},
  std::byte{0x24},
  std::byte{0xb5},
  std::byte{0x36},
  std::byte{0x5d},
  std::byte{0x99},
  std::byte{0xa2},
  std::byte{0x91},
  std::byte{0x80},
  std::byte{0xa7},
  std::byte{0x11},
  std::byte{0x39},
  std::byte{0x48},
  std::byte{0xe7},
  std::byte{0x35},
  std::byte{0x30},
  std::byte{0xca},
  std::byte{0x8b},
  std::byte{0x30},
  std::byte{0x31},
  std::byte{0x1c},
};
