// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Granit contributors

// 由 granit_shader_tool object-ids 生成。

constexpr std::array<std::byte, 32> minimal_vertex_id{
  std::byte{0xf9},
  std::byte{0xc7},
  std::byte{0xe9},
  std::byte{0xb6},
  std::byte{0xdb},
  std::byte{0xf7},
  std::byte{0x49},
  std::byte{0xf9},
  std::byte{0x41},
  std::byte{0x77},
  std::byte{0x62},
  std::byte{0x15},
  std::byte{0x62},
  std::byte{0x94},
  std::byte{0xaa},
  std::byte{0x2b},
  std::byte{0x1e},
  std::byte{0xc0},
  std::byte{0x56},
  std::byte{0x36},
  std::byte{0x2e},
  std::byte{0x00},
  std::byte{0x5f},
  std::byte{0x29},
  std::byte{0x77},
  std::byte{0x06},
  std::byte{0xf7},
  std::byte{0x0c},
  std::byte{0x3d},
  std::byte{0xdd},
  std::byte{0x48},
  std::byte{0xe8},
};
