# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Granit contributors

if(NOT DEFINED GRANIT_SOURCE_DIR)
  message(FATAL_ERROR "必须通过 GRANIT_SOURCE_DIR 指定仓库根目录")
endif()

set(action "${GRANIT_SOURCE_DIR}/.github/actions/setup-shader-toolchain/action.yml")
if(NOT EXISTS "${action}")
  message(FATAL_ERROR "缺少统一 Shader 工具链 Action")
endif()
file(READ "${action}" action_content)
foreach(required_text IN ITEMS "download_shader_toolchain.cmake" "root=$root")
  string(FIND "${action_content}" "${required_text}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "Shader 工具链 Action 缺少契约：${required_text}")
  endif()
endforeach()

foreach(workflow IN ITEMS windows.yml linux.yml release.yml)
  file(READ "${GRANIT_SOURCE_DIR}/.github/workflows/${workflow}" content)
  string(FIND "${content}" "uses: ./.github/actions/setup-shader-toolchain" action_position)
  string(FIND "${content}" "steps.shader-toolchain.outputs.root" output_position)
  if(action_position EQUAL -1 OR output_position EQUAL -1)
    message(FATAL_ERROR "${workflow} 未统一消费 Shader 工具链 Action 输出")
  endif()
  if(content MATCHES "granit-shader-toolchain-v[0-9]")
    message(FATAL_ERROR "${workflow} 仍硬编码带版本的 Shader 工具链目录")
  endif()
endforeach()
