# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Granit contributors

if(NOT DEFINED MODULE OR NOT EXISTS "${MODULE}")
  message(FATAL_ERROR "必须提供可用的 GranitShaderToolchain.cmake")
endif()

set(GRANIT_SHADER_TOOLCHAIN_MODE off CACHE STRING "" FORCE)
set(GRANIT_DXC_EXECUTABLE "should-be-cleared" CACHE FILEPATH "" FORCE)
set(GRANIT_TINT_EXECUTABLE "should-be-cleared" CACHE FILEPATH "" FORCE)
include("${MODULE}")
granit_find_shader_toolchain()
if(GRANIT_DXC_EXECUTABLE OR GRANIT_TINT_EXECUTABLE)
  message(FATAL_ERROR "off 模式未清除 Shader 工具路径")
endif()
if(NOT GRANIT_SHADER_TOOLCHAIN_RELEASE_TAG OR NOT GRANIT_SHADER_TOOLCHAIN_ARCHIVE_SHA256 OR
   NOT GRANIT_SHADER_TOOLCHAIN_PACKAGE_NAME)
  message(FATAL_ERROR "Shader Toolchain 锁定元数据不完整")
endif()

if(NOT DEFINED WORK_DIR)
  set(WORK_DIR "${CMAKE_CURRENT_BINARY_DIR}/shader-toolchain-mode-test")
endif()
set(work_dir "${WORK_DIR}")
file(REMOVE_RECURSE "${work_dir}")
if(CMAKE_HOST_WIN32)
  set(dxc_name dxc.exe)
  set(tint_name tint.exe)
else()
  set(dxc_name dxc)
  set(tint_name tint)
endif()

set(common_root "${work_dir}/common")
file(MAKE_DIRECTORY "${common_root}/bin")
file(COPY_FILE "${CMAKE_COMMAND}" "${common_root}/bin/${dxc_name}")
file(COPY_FILE "${CMAKE_COMMAND}" "${common_root}/bin/${tint_name}")
set(GRANIT_SHADER_TOOLCHAIN_MODE system CACHE STRING "" FORCE)
set(GRANIT_SHADER_TOOLCHAIN_POLICY unchecked CACHE STRING "" FORCE)
set(GRANIT_SHADER_TOOLCHAIN_ROOT "" CACHE PATH "" FORCE)
set(GRANIT_DXC_EXECUTABLE "${common_root}/bin/${dxc_name}" CACHE FILEPATH "" FORCE)
set(GRANIT_TINT_EXECUTABLE "${common_root}/bin/${tint_name}" CACHE FILEPATH "" FORCE)
granit_find_shader_toolchain()
file(REAL_PATH "${common_root}" expected_common_root)
if(NOT GRANIT_SHADER_TOOLCHAIN_ROOT STREQUAL expected_common_root)
  message(FATAL_ERROR "system 模式未从共同 bin 目录推导 Toolchain 根目录")
endif()

file(MAKE_DIRECTORY "${work_dir}/split-dxc/bin" "${work_dir}/split-tint/bin")
file(COPY_FILE "${CMAKE_COMMAND}" "${work_dir}/split-dxc/bin/${dxc_name}")
file(COPY_FILE "${CMAKE_COMMAND}" "${work_dir}/split-tint/bin/${tint_name}")
set(GRANIT_SHADER_TOOLCHAIN_ROOT "" CACHE PATH "" FORCE)
set(GRANIT_DXC_EXECUTABLE "${work_dir}/split-dxc/bin/${dxc_name}" CACHE FILEPATH "" FORCE)
set(GRANIT_TINT_EXECUTABLE "${work_dir}/split-tint/bin/${tint_name}" CACHE FILEPATH "" FORCE)
granit_find_shader_toolchain()
if(GRANIT_SHADER_TOOLCHAIN_ROOT OR GRANIT_DXC_EXECUTABLE OR GRANIT_TINT_EXECUTABLE)
  message(FATAL_ERROR "system 模式错误接受了分离的 DXC 与 Tint")
endif()
