// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Granit contributors

#ifndef GRANIT_WINDOW_INPUT_NATIVE_EVENT_H_
#define GRANIT_WINDOW_INPUT_NATIVE_EVENT_H_

#include <granit/window/window.h>

#include <stdint.h>

#define GRANIT_WINDOW_INPUT_BACKEND_WIN32 UINT32_C(1)
#define GRANIT_WINDOW_INPUT_BACKEND_XCB UINT32_C(2)
#define GRANIT_WINDOW_INPUT_BACKEND_WAYLAND UINT32_C(3)
#define GRANIT_WINDOW_INPUT_BACKEND_EMSCRIPTEN UINT32_C(4)
#define GRANIT_WINDOW_INPUT_BACKEND_SDL3 UINT32_C(5)

#define GRANIT_WINDOW_INPUT_SDL3_KEY_DOWN UINT32_C(1)
#define GRANIT_WINDOW_INPUT_SDL3_KEY_UP UINT32_C(2)
#define GRANIT_WINDOW_INPUT_SDL3_TEXT UINT32_C(3)
#define GRANIT_WINDOW_INPUT_SDL3_POINTER_MOTION UINT32_C(4)
#define GRANIT_WINDOW_INPUT_SDL3_POINTER_DOWN UINT32_C(5)
#define GRANIT_WINDOW_INPUT_SDL3_POINTER_UP UINT32_C(6)
#define GRANIT_WINDOW_INPUT_SDL3_POINTER_WHEEL UINT32_C(7)
#define GRANIT_WINDOW_INPUT_SDL3_POINTER_ENTER UINT32_C(8)
#define GRANIT_WINDOW_INPUT_SDL3_POINTER_LEAVE UINT32_C(9)

#define GRANIT_WINDOW_INPUT_WAYLAND_KEYMAP UINT32_C(1)
#define GRANIT_WINDOW_INPUT_WAYLAND_KEY UINT32_C(2)
#define GRANIT_WINDOW_INPUT_WAYLAND_MODIFIERS UINT32_C(3)
#define GRANIT_WINDOW_INPUT_WAYLAND_POINTER_ENTER UINT32_C(4)
#define GRANIT_WINDOW_INPUT_WAYLAND_POINTER_LEAVE UINT32_C(5)
#define GRANIT_WINDOW_INPUT_WAYLAND_POINTER_MOTION UINT32_C(6)
#define GRANIT_WINDOW_INPUT_WAYLAND_POINTER_BUTTON UINT32_C(7)
#define GRANIT_WINDOW_INPUT_WAYLAND_POINTER_AXIS UINT32_C(8)

#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_KEY_DOWN UINT32_C(1)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_KEY_UP UINT32_C(2)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_TEXT UINT32_C(3)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_MOUSE_MOVE UINT32_C(4)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_MOUSE_DOWN UINT32_C(5)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_MOUSE_UP UINT32_C(6)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_WHEEL UINT32_C(7)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_MOUSE_ENTER UINT32_C(8)
#define GRANIT_WINDOW_INPUT_EMSCRIPTEN_MOUSE_LEAVE UINT32_C(9)

typedef struct granit_window_input_native_event {
  uint32_t backend;
  uint32_t type;
  uintptr_t word;
  intptr_t value;
  int32_t x;
  int32_t y;
  uint32_t state;
  uint32_t detail;
  uint32_t data0;
  uint32_t data1;
} granit_window_input_native_event;

#endif
