// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Granit contributors

#ifndef GRANIT_TESTS_ABI_SNAPSHOTS_0_36_0_WINDOW_LAYOUT_H_
#define GRANIT_TESTS_ABI_SNAPSHOTS_0_36_0_WINDOW_LAYOUT_H_

#include "platform_identity.h"

#define GRANIT_ABI_036_WINDOW_SYSTEM_DESC_SIZE 16
#define GRANIT_ABI_036_WINDOW_DESC_SIZE 48
#define GRANIT_ABI_036_WINDOW_DESC_TARGET 40
#define GRANIT_ABI_036_WINDOW_EVENT_SIZE 56
#define GRANIT_ABI_036_INPUT_EVENT_SIZE 88
#define GRANIT_ABI_036_KEYBOARD_STATE_SIZE 64
#define GRANIT_ABI_036_POINTER_STATE_SIZE 40

#endif
