// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Granit contributors

#ifndef GRANIT_PIPELINE_PBR_MATERIAL_H_
#define GRANIT_PIPELINE_PBR_MATERIAL_H_

#include <stdint.h>

#include <granit/pipeline/export.h>
#include <granit/renderer/pipeline.h>

typedef uint32_t granit_pbr_texture_flags;
#define GRANIT_PBR_MATERIAL_TEMPLATE_VERSION UINT32_C(4)
#define GRANIT_PBR_MATERIAL_CONTENT_HASH_HEX                                                       \
  "d30305713f07b6e9068b9e1f2fa700304d858ee7b2e738870790da3dfa15dee9"
#define GRANIT_PBR_TEXTURE_BASE_COLOR (UINT32_C(1) << 0)
#define GRANIT_PBR_TEXTURE_METALLIC_ROUGHNESS (UINT32_C(1) << 1)
#define GRANIT_PBR_TEXTURE_NORMAL (UINT32_C(1) << 2)
#define GRANIT_PBR_TEXTURE_OCCLUSION (UINT32_C(1) << 3)
#define GRANIT_PBR_TEXTURE_EMISSIVE (UINT32_C(1) << 4)
#define GRANIT_PBR_TEXTURE_ALL                                                                     \
  (GRANIT_PBR_TEXTURE_BASE_COLOR | GRANIT_PBR_TEXTURE_METALLIC_ROUGHNESS |                         \
   GRANIT_PBR_TEXTURE_NORMAL | GRANIT_PBR_TEXTURE_OCCLUSION | GRANIT_PBR_TEXTURE_EMISSIVE)

#define GRANIT_PBR_TEXTURE_FEATURE_NAME "pbr_texture_mask"
#define GRANIT_PBR_PARAMETER_BASE_COLOR "base_color"
#define GRANIT_PBR_PARAMETER_METALLIC "metallic"
#define GRANIT_PBR_PARAMETER_PERCEPTUAL_ROUGHNESS "perceptual_roughness"
#define GRANIT_PBR_PARAMETER_NORMAL_SCALE "normal_scale"
#define GRANIT_PBR_PARAMETER_OCCLUSION_STRENGTH "occlusion_strength"
#define GRANIT_PBR_PARAMETER_EMISSIVE "emissive"
#define GRANIT_PBR_PARAMETER_DEBUG_DISPLAY "debug_display"
#define GRANIT_PBR_PARAMETER_BASE_COLOR_TEXTURE "base_color_texture"
#define GRANIT_PBR_PARAMETER_METALLIC_ROUGHNESS_TEXTURE "metallic_roughness_texture"
#define GRANIT_PBR_PARAMETER_NORMAL_TEXTURE "normal_texture"
#define GRANIT_PBR_PARAMETER_OCCLUSION_TEXTURE "occlusion_texture"
#define GRANIT_PBR_PARAMETER_EMISSIVE_TEXTURE "emissive_texture"
#define GRANIT_PBR_PARAMETER_SAMPLER "pbr_sampler"

#define GRANIT_PBR_CONSTANT_BUFFER_SIZE UINT32_C(48)
#define GRANIT_PBR_CONSTANT_BASE_COLOR_OFFSET UINT32_C(0)
#define GRANIT_PBR_CONSTANT_METALLIC_OFFSET UINT32_C(16)
#define GRANIT_PBR_CONSTANT_PERCEPTUAL_ROUGHNESS_OFFSET UINT32_C(20)
#define GRANIT_PBR_CONSTANT_NORMAL_SCALE_OFFSET UINT32_C(24)
#define GRANIT_PBR_CONSTANT_OCCLUSION_STRENGTH_OFFSET UINT32_C(28)
#define GRANIT_PBR_CONSTANT_EMISSIVE_OFFSET UINT32_C(32)
#define GRANIT_PBR_CONSTANT_DEBUG_DISPLAY_OFFSET UINT32_C(44)

#define GRANIT_PBR_BINDING_CONSTANTS UINT32_C(0)
#define GRANIT_PBR_BINDING_BASE_COLOR UINT32_C(1)
#define GRANIT_PBR_BINDING_METALLIC_ROUGHNESS UINT32_C(2)
#define GRANIT_PBR_BINDING_NORMAL UINT32_C(3)
#define GRANIT_PBR_BINDING_OCCLUSION UINT32_C(4)
#define GRANIT_PBR_BINDING_EMISSIVE UINT32_C(5)
#define GRANIT_PBR_BINDING_SAMPLER UINT32_C(6)

#define GRANIT_PBR_VERTEX_LOCATION_POSITION UINT32_C(0)
#define GRANIT_PBR_VERTEX_LOCATION_NORMAL UINT32_C(1)
#define GRANIT_PBR_VERTEX_LOCATION_TANGENT UINT32_C(2)
#define GRANIT_PBR_VERTEX_LOCATION_UV0 UINT32_C(3)

typedef uint32_t granit_pbr_vertex_layout_result;
#define GRANIT_PBR_VERTEX_LAYOUT_VALID UINT32_C(0)
#define GRANIT_PBR_VERTEX_LAYOUT_INVALID_TEXTURE_FLAGS UINT32_C(1)
#define GRANIT_PBR_VERTEX_LAYOUT_MISSING_POSITION UINT32_C(2)
#define GRANIT_PBR_VERTEX_LAYOUT_MISSING_NORMAL UINT32_C(3)
#define GRANIT_PBR_VERTEX_LAYOUT_MISSING_UV0 UINT32_C(4)
#define GRANIT_PBR_VERTEX_LAYOUT_MISSING_TANGENT UINT32_C(5)
#define GRANIT_PBR_VERTEX_LAYOUT_INVALID_ARGUMENT UINT32_C(6)

#ifdef __cplusplus
extern "C" {
#endif

/** 检查公共顶点布局是否满足指定标准 PBR 纹理变体。 */
GRANIT_RENDER_PIPELINE_API granit_pbr_vertex_layout_result
granit_pbr_validate_vertex_layout(const granit_vertex_buffer_layout* vertex_buffers,
                                  uint32_t vertex_buffer_count, granit_pbr_texture_flags textures);

#ifdef __cplusplus
}
#endif

#endif
