
set(GRANIT_TESTING_ENABLED OFF)
if(GRANIT_BUILD_TESTING AND BUILD_TESTING)
  set(GRANIT_TESTING_ENABLED ON)
endif()

set(GRANIT_NEEDS_SHADER_TOOLCHAIN OFF)
if(GRANIT_HAS_NATIVE_TOOLS AND
   (GRANIT_BUILD_TOOLS OR GRANIT_BUILD_ASSET_TOOLS OR GRANIT_BUILD_EXAMPLES OR
    GRANIT_BUILD_BENCHMARKS OR GRANIT_TESTING_ENABLED))
  set(GRANIT_NEEDS_SHADER_TOOLCHAIN ON)
endif()

set(GRANIT_NEEDS_TOOLS OFF)
set(GRANIT_NEEDS_ASSET_TOOLS OFF)
if(GRANIT_HAS_NATIVE_TOOLS AND
   (GRANIT_BUILD_TOOLS OR GRANIT_BUILD_ASSET_TOOLS OR
    GRANIT_BUILD_EXAMPLES OR GRANIT_BUILD_BENCHMARKS OR GRANIT_TESTING_ENABLED))
  set(GRANIT_NEEDS_TOOLS ON)
  set(GRANIT_NEEDS_ASSET_TOOLS ON)
endif()

set(GRANIT_NEEDS_SDL3 OFF)
if(GRANIT_BUILD_INTEGRATION_SDL3 OR GRANIT_BUILD_EXAMPLES OR GRANIT_ENABLE_WINDOW_SDL3)
  set(GRANIT_NEEDS_SDL3 ON)
endif()

set(GRANIT_NEEDS_IMGUI OFF)
if(GRANIT_BUILD_INTEGRATION_IMGUI OR GRANIT_BUILD_EXAMPLES)
  set(GRANIT_NEEDS_IMGUI ON)
endif()
